// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tcfesifuvwolsyhnmppv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRjZmVzaWZ1dndvbHN5aG5tcHB2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NzQ0ODgsImV4cCI6MjA2NjM1MDQ4OH0.-Rf27YGqAPgi2z0fqIZ54NnSuhVKBl0TwYvYw5tbBtQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);